### ISSUE TITLE
1.4 release checklist

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/fdotoolbox#49]
* [x] Make sure git commit hash is baked into assembly info
 * [x] Fix broken application icon
 * [ ] Fix about dialog so description is properly formatted and git hash is not squished
 * [x] Fix user guide link
 * [x] Publish v1.4.0 userdoc to GH pages (#47)
